"""
Mapping des comptes 4 chiffres vers leurs intitulés.
Source: Plan comptable marocain normalisé.
"""

ACCOUNT_LABELS = {
    "1111": "Capital social",
    "1112": "Fonds de dotation",
    "1117": "Capital personnel",
    "1119": "Actionnaires, capital souscrit-non appelé",
    "1121": "Primes d'émission",
    "1122": "Primes de fusion",
    "1123": "Primes d'apport",
    "1130": "Ecarts de réévaluation",
    "1140": "Réserve légale",
    "1151": "Réserves statutaires ou contractuelles",
    "1152": "Réserves facultatives",
    "1155": "Réserves réglementées",
    "1161": "Report à nouveau (solde créditeur)",
    "1169": "Report à nouveau (solde débiteur)",
    "1181": "Résultats nets en instance d'affectation (solde créditeur)",
    "1189": "Résultats nets en instance d'affectation (solde débiteur)",
    "1191": "Résultat net de l'exercice (solde créditeur)",
    "1199": "Résultat net de l'exercice (solde débiteur)",
    "1311": "Subventions d'investissement reçues",
    "1319": "Subventions d'investissement inscrites au CPC",
    "1351": "Provisions pour amortissements dérogatoires",
    "1352": "Provisions pour plus-values en instance d'imposition",
    "1354": "Provisions pour investissements",
    "1355": "Provisions pour reconstitution des gisements",
    "1356": "Provisions pour acquisition et construction de logements",
    "1358": "Autres provisions réglementées",
    "1410": "Emprunts obligataires",
    "1481": "Emprunts auprès des établissements de crédit",
    "1482": "Avances de l'Etat",
    "1483": "Dettes rattachées à des participations",
    "1484": "Billets de fonds",
    "1485": "Avances reçues et comptes courants bloqués",
    "1486": "Fournisseurs d'immobilisation",
    "1487": "Dépôts et cautionnements reçues",
    "1488": "Dettes de financement diverses",
    "1511": "Provisions pour litiges",
    "1512": "Provisions pour garanties données aux clients",
    "1513": "Provisions pour propre assureur",
    "1514": "Provision pour pertes sur marchés à terme",
    "1515": "Provisions pour amendes, double droits, pénalités",
    "1516": "Provisions pour pertes de change",
    "1518": "Autres provisions pour risques",
    "1551": "Provisions pour impôts",
    "1552": "Provisions pour pensions de retraite et obligations similaires",
    "1555": "Provisions pour charges à répartir sur plusieurs exercices",
    "1558": "Autres provisions pour charges",
    "1601": "Comptes de liaison du siège",
    "1605": "Comptes de liaison des établissements",
    "1710": "Augmentation des créances immobilisées",
    "1720": "Diminution des dettes de financement",
    "2111": "Frais de constitution",
    "2112": "Frais préalables au démarrage",
    "2113": "Frais d'augmentation du capital",
    "2114": "Frais sur opérations de fusions, scissions et transformations",
    "2116": "Frais de prospection",
    "2117": "Frais de publicité",
    "2118": "Autres frais préliminaires",
    "2121": "Frais d'acquisitition des immobilisations",
    "2125": "Frais d'émission des emprunts",
    "2128": "Autres charges à répartir",
    "2130": "Primes de remboursement des obligations",
    "2210": "Immobilisation en recherche et développement",
    "2220": "Brevets, marques, droits et valeurs similaires",
    "2230": "Fonds commercial",
    "2285": "Autres immobilisations incorporelles",
    "2311": "Terrains nus",
    "2312": "Terrains aménagés",
    "2313": "Terrains bâtis",
    "2314": "Terrains de gisement",
    "2316": "Agencements et aménagements de terrains",
    "2318": "Autres terrains",
    "2321": "Bâtiments",
    "2323": "Constructions sur terrains d'autrui",
    "2325": "Ouvrages d'infrastructure",
    "2327": "Agencements et aménagements des constructions",
    "2328": "Autres constructions",
    "2331": "Installations techniques",
    "2332": "Matériel et outillage",
    "2333": "Emballages récupérables identifiables",
    "2338": "Autres installations techniques, matériel et outillage",
    "2340": "Matériel de transport",
    "2351": "Mobilier de bureau",
    "2352": "Matériel de bureau",
    "2355": "Matériel informatique",
    "2356": "Agencements, installations et aménagements divers (biens n'appartenant pas à l'entreprise)",
    "2358": "Autres mobilier, matériel de bureau et aménagements divers",
    "2380": "Autres immobilisations corporelles",
    "2392": "Immobilisations corporelles en cours des terrains et constructions",
    "2393": "Immobilisations corporelles en cours des installations techniques, matériel et outillage",
    "2394": "Immobilisations corporelles en cours de matériel de transport",
    "2395": "Immobilisations corporelles en cours de mobilier, matériel de bureau et aménagements divers",
    "2397": "Avances et acomptes versés sur commandes d'immobilisations corporelles",
    "2398": "Autres immobilisations corporelles en cours",
    "2415": "Prêts aux associés",
    "2416": "Billets de fonds",
    "2418": "Autres prêts",
    "2441": "Prêts au personnel",
    "2481": "Titres immobilisés (droits de créance)",
    "2483": "Créances rattachées à des participations",
    "2486": "Dépôts et cautionnements versés",
    "2487": "Créances immobilisées",
    "2488": "Créances financères diverses",
    "2510": "Titres de participation",
    "2581": "Actions",
    "2588": "Titres divers",
    "2710": "Diminution des créances immobilisées",
    "2720": "Augmentation des dettes de financement",
    "2811": "Amortissements des frais préliminaires",
    "2812": "Amortissements des charges à répartir",
    "2813": "Amortissements des primes de remboursement des obligations",
    "2821": "Amortissements de l'immobilisation en recherche et développement",
    "2822": "Amortissements des brevets, marques, droits et valeurs similaires",
    "2823": "Amortissements du fonds commercial",
    "2828": "Amortissements des autres immobilisations incorporelles",
    "2831": "Amortissements des terrains",
    "2832": "Amortissements des constructions",
    "2833": "Amortissements des installations techniques, matériel et outillage",
    "2834": "Amortissements du matériel de transport",
    "2835": "Amortissements du mobilier, matériel de bureau et aménagements divers",
    "2838": "Amortissements des autres immobilisations corporelles",
    "2920": "Provisions pour dépréciation des immobilisations incorporelles",
    "2930": "Provisions pour dépréciation des immobilisations corporelles",
    "2941": "Provisions pour dépréciation des prêts immobilisés",
    "2948": "Provisions pour dépréciation des autres créances financières",
    "2951": "Provisions pour dépréciation des titres de participation",
    "2958": "Provisions pour dépréciation des autres titres immobilisés",
    "3111": "Marchandises (groupe A)",
    "3112": "Marchandises (groupe B)",
    "3116": "Marchandises en cours de route",
    "3118": "Autres marchandises",
    "3121": "Matières premières",
    "3122": "Matières et fournitures consommables",
    "3123": "Emballages",
    "3126": "Matières et fournitures consommables en cours de route",
    "3128": "Autres matières et fournitures consommables",
    "3131": "Biens en cours",
    "3134": "Services en cours",
    "3138": "Autres produits en cours",
    "3141": "Produits intermédiaires",
    "3145": "Produits résiduels (ou matières de récupération)",
    "3148": "Autres produits intermédiaires et produits résiduels",
    "3151": "Produits finis (groupe A)",
    "3152": "Produits finis (groupe B)",
    "3156": "Produits finis en cours de route",
    "3158": "Autres produits finis",
    "3411": "Fournisseurs - avances et acomptes versés sur commandes d'exploitation",
    "3413": "Fournisseurs - créances pour emballages et matériel à rendre",
    "3417": "Rabais, remises et ristournes à obtenir - avoirs non encore reçus",
    "3418": "Autres fournisseurs débiteurs",
    "3421": "Clients",
    "3423": "Clients - retenues de garantie",
    "3424": "Clients douteux ou litigieux",
    "3425": "Clients - effets à recevoir",
    "3427": "Clients - factures à établir et créances sur travaux non encore facturés",
    "3428": "Autres clients et comptes rattachés",
    "3431": "Avances et acomptes au personnel",
    "3438": "Personnel - autres débiteurs",
    "3451": "Subventions à recevoir",
    "3453": "Acomptes sur impôts sur les résultats",
    "3455": "Etat - TVA récupérable",
    "3456": "Etat - crédit de TVA (suivant déclaration)",
    "3458": "Etat - autres comptes débiteurs",
    "3461": "Associés - comptes d'apport en société",
    "3462": "Actionnaires - capital souscrit et appelé non versé",
    "3463": "Comptes courants des associés débiteurs",
    "3464": "Associés - opérations faites en commun",
    "3467": "Créances rattachées aux comptes d'associés",
    "3468": "Autres comptes d'associés débiteurs",
    "3481": "Créances sur cessions d'immobilisations",
    "3482": "Créances sur cessions d'éléments d'actif circulant",
    "3487": "Créances rattachées aux autres débiteurs",
    "3488": "Divers débiteurs",
    "3491": "Charges constatées d'avance",
    "3493": "Intérêts courus et non échus à percevoir",
    "3495": "Comptes de répartition périodique des charges",
    "3497": "Comptes transitoires ou d'attente - débiteurs",
    "3501": "Actions, partie libérée",
    "3502": "Actions, partie non libérée",
    "3504": "Obligations",
    "3506": "Bons de caisse et bons de trésor",
    "3508": "Autres titres et valeurs de placement similaires",
    "3701": "Diminution des créances circulantes",
    "3702": "Augmentation des dettes circulantes",
    "3911": "Provisions pour dépréciation des marchandises",
    "3912": "Provisions pour dépréciation des matières et fournitures",
    "3913": "Provisions pour dépréciation des produits en cours",
    "3914": "Provisions pour dépréciation des produits intermédiaires",
    "3915": "Provisions pour dépréciation des produits finis",
    "3941": "Provisions pour dépréciation - fournisseurs débiteurs, avances et acomptes",
    "3942": "Provisions pour dépréciation des clients et comptes rattachés",
    "3943": "Provisions pour dépréciation du personnel - débiteur",
    "3946": "Provisions pour dépréciation des comptes d'associés débiteurs",
    "3948": "Provisions pour dépréciation des autres débiteurs",
    "3950": "Provisions pour dépréciation des titres et valeurs de placement",
    "4411": "Fournisseurs",
    "4413": "Fournisseurs - retenues de garantie",
    "4415": "Fournisseurs - effets à payer",
    "4417": "Fournisseurs - factures non parvenues",
    "4418": "Autres fournisseurs et comptes rattachés",
    "4421": "Clients - avances et acomptes reçus sur commandes en cours",
    "4425": "Clients - dettes pour emballages et matériel consignés",
    "4427": "Rabais, remises et ristournes à accorder - avoirs à établir",
    "4428": "Autres clients créditeurs",
    "4432": "Rémunérations dues au personnel",
    "4433": "Dépôts du personnel créditeurs",
    "4434": "Oppositions sur salaires",
    "4437": "Charges du personnel à payer",
    "4438": "Personnel - autres créditeurs",
    "4441": "Caisse Nationale de la Sécurité Sociale",
    "4443": "Caisses de retraite",
    "4445": "Mutuelles",
    "4447": "Charges sociales à payer",
    "4448": "Autres organismes sociaux",
    "4452": "Etat Impôts, taxes et assimilés",
    "4453": "Etat, impôts sur les résultats",
    "4455": "Etat, TVA facturée",
    "4456": "Etat, TVA due (suivant déclarations)",
    "4457": "Etat, impôts et taxes à payer",
    "4458": "Etat - autres comptes créditeurs",
    "4461": "Associés - capital à rembourser",
    "4462": "Associés - versements reçus sur augmentation de capital",
    "4463": "Comptes courants des associés créditeurs",
    "4464": "Associés - opérations faites en commun",
    "4465": "Associés - dividendes à payer",
    "4468": "Autres comptes d'associés - créditeurs",
    "4481": "Dettes sur acquisitions d'immobilisations",
    "4483": "Dettes sur acquisitions de titres et valeurs de placement",
    "4484": "Obligations échues à rembourser",
    "4485": "Obligations, coupons à payer",
    "4487": "Dettes rattachées aux autres créanciers",
    "4488": "Divers créanciers",
    "4491": "Produits constatés d'avance",
    "4493": "Intérêts courus et non échus à payer",
    "4495": "Comptes de répartition périodique des produits",
    "4497": "Comptes transitoires ou d'attente - créditeurs",
    "4501": "Provisions pour litiges",
    "4502": "Provisions pour garanties données aux clients",
    "4505": "Provisions pour amendes, doubles droits et pénalités",
    "4506": "Provisions pour pertes de change",
    "4507": "Provisions pour impôts",
    "4508": "Autres provisions pour risques et charges",
    "4701": "Augmentation des créances circulantes",
    "4702": "Diminution des dettes circulantes",
    "5111": "Chèques à encaisser ou à l'encaissement",
    "5113": "Effets à encaisser ou à l'encaissement",
    "5115": "Virement de fonds",
    "5118": "Autres valeurs à encaisser",
    "5141": "Banques (solde débiteur)",
    "5143": "Trésorerie Générale",
    "5146": "Chèques postaux",
    "5148": "Autres établissements financiers et assimilés (soldes débiteurs)",
    "5161": "Caisses",
    "5165": "Régies d'avances et accréditifs",
    "5520": "Crédits d'escompte",
    "5530": "Crédits de trésorerie",
    "5541": "Banques (solde créditeur)",
    "5548": "Autres établissements financiers et assimilés (soldes créditeurs)",
    "5900": "Provisions pour dépréciation des comptes de trésorerie",
    "6111": "Achats de marchandises \"groupe A\"",
    "6112": "Achats de marchandises \"groupe B\"",
    "6114": "Variation de stocks de marchandises",
    "6118": "Achats revendus de marchandises des exercices antérieurs",
    "6119": "Rabais, remises et ristournes obtenus sur achats de marchandises",
    "6121": "Achats de matières premières",
    "6122": "Achats de matières et fournitures consommables",
    "6123": "Achats d'emballages",
    "6124": "Variation des stocks de matières et fournitures",
    "6125": "Achats non stockés de matières et fournitures",
    "6126": "Achats de travaux, études et prestations de service",
    "6128": "Achats de matières et de fournitures des exercices antérieurs",
    "6129": "Rabais, remises et ristournes obtenus sur achats consommés de matières et fournitures",
    "6131": "Locations et charges locatives",
    "6132": "Redevances de crédit-bail",
    "6133": "Entretien et réparations",
    "6134": "Primes d'assurances",
    "6135": "Rémunérations du personnel extérieur à l'entreprise",
    "6136": "Rémunérations d'intermédiaires et honoraires",
    "6137": "Redevances pour brevets, marques, droits et valeurs similaires",
    "6141": "Etudes, recherches et documentation",
    "6142": "Transports",
    "6143": "Déplacements, missions et réceptions",
    "6144": "Publicité, publications et relations publiques",
    "6145": "Frais postaus et frais de télécommunications",
    "6146": "Cotisations et dons",
    "6147": "Services bancaires",
    "6148": "Autres charges externes des exercices antérieurs",
    "6149": "Rabais, remises et ristournes obtenus sur autres charges externes",
    "6161": "Impôts et taxes directs",
    "6165": "Impôts et taxes directs",
    "6167": "Impôts, taxes et droits assimilés",
    "6168": "Impôts et taxes des exercices antérieurs",
    "6171": "Rémunérations du personnel",
    "6174": "Charges sociales",
    "6176": "Charges sociales diverses",
    "6177": "Rémunération de l'exploitant",
    "6178": "Charges du personnel des exercices antérieurs",
    "6181": "Jetons de présence",
    "6182": "Pertes sur créances irrécouvrables",
    "6185": "Pertes sur opérations faites en commun",
    "6186": "Transfert de profits sur opérations faites en commun",
    "6188": "Autres charges d'exploitation des exercices antérieurs",
    "6191": "Dotations d'exploitation aux amortissements de l'immobilisation en non valeur",
    "6192": "Dotations d'exploitation aux amortissements des immobilisations incorporelles",
    "6193": "Dotations d'exploitation aux amortissements des immobilisations corporelles",
    "6194": "Dotations d'exploitation aux provisions pour dépréciation des immobilisations",
    "6195": "Dotations d'exploitation aux provisions pour risques et charges",
    "6196": "Dotations d'exploitation aux provisions pour dépréciations de l'actif circulant",
    "6198": "Dotations d'exploitation des exercices antérieurs",
    "6311": "Intérêts des emprunts et dettes",
    "6318": "Charges d'intérêts des exercices antérieurs",
    "6331": "Pertes de change propres à l'exercice",
    "6338": "Pertes de change des exercices antérieurs",
    "6382": "Pertes sur créances liées à des participations",
    "6385": "Charges nettes sur cession de titres et valeurs de placement",
    "6386": "Escomptes accordés",
    "6388": "Autres charges financières des exercices antérieurs",
    "6391": "Dotations aux amortissements des primes de remboursement des obligations",
    "6392": "Dotations aux provisions pour dépréciations des immobilisations financières",
    "6393": "Dotations aux provisions pour risques et charges financières",
    "6394": "Dotation aux provisions pour dépréciation des titres et valeurs de placement",
    "6396": "Dotations aux provisions pour dépréciation des compte de trésoreie",
    "6398": "Dotations financières des exercices antérieurs",
    "6512": "VNA des immobilisations incorporelles cédées",
    "6513": "VNA des immobilisations corporelles cédées",
    "6514": "VNA provisions des immobilisations financières cédées (droits de propriété)",
    "6518": "VNA des immobilisations cédées des exercices antérieurs",
    "6561": "Subventions accordées de l'exercice",
    "6568": "Subventions accordées des exercices antérieurs",
    "6581": "Pénalités sur marchés et dédits",
    "6582": "Rappels d'impôts (autres qu'impôts sur les résultats)",
    "6583": "Pénalités et amendes fiscales ou pénales",
    "6585": "Créances devenues irrécouvrables",
    "6586": "Dons, libéralités et lots",
    "6588": "Autres charges non courantes des exercices antérieurs",
    "6591": "Dotations aux amortissements exceptionnels des immobilisations",
    "6594": "Dotations non courantes aux provisions réglementées",
    "6595": "Dotations non courantes aux provisions pour risques et charges",
    "6596": "Dotations non courantes aux provisions pour dépréciation",
    "6598": "Dotations non courantes des exercices antérieurs",
    "6701": "Impôts sur les bénéfices",
    "6705": "Imposition minimale annuelle des sociétés",
    "6708": "Rappels et dégrèvements d'impôts sur les résultats",
    "7111": "Ventes de marchandises au Maroc",
    "7113": "Ventes de marchandises à l'étranger",
    "7118": "Ventes de marchandises des exercices antérieurs",
    "7119": "Rabais, remises et ristournes accordés par l'entreprise",
    "7121": "Ventes de biens produits au Maroc",
    "7122": "Ventes de biens produits à l'étranger",
    "7124": "Ventes de services produits au Maroc",
    "7125": "Ventes de services produits à l'étranger",
    "7126": "Redevances pour brevets, marques, droits et valeurs similaires",
    "7127": "Ventes de produits accessoires",
    "7128": "Ventes de biens et services produits des exercices antérieurs",
    "7129": "Rabais, remises et ristournes accordés par l'entreprise",
    "7131": "Variation des stocks de produits en cours",
    "7132": "Variation des stocks de biens produits",
    "7134": "Variation des stocks de services en cours",
    "7141": "Immobilisation en non valeurs produite",
    "7142": "Immobilisations incorporelles produites",
    "7143": "Immobilisations corporelles produites",
    "7148": "Immobilisations produites des exercices antérieurs",
    "7161": "Subventions d'exploitations reçues de l'exercice",
    "7168": "Subventions d'exploitation reçues des exercices antérieurs",
    "7181": "Jetons de présence reçus",
    "7182": "Revenus des immeubles non affectés à l'exploitation",
    "7185": "Profits sur opérations faites en commun",
    "7186": "Transfert de pertes sur opérations faites en commun",
    "7188": "Autres produits d'exploitation des exercices antérieurs",
    "7191": "Reprises sur amortissements de l'immobilisation en non valeurs",
    "7192": "Reprises sur amortissements des immobilisations incorporelles",
    "7193": "Reprises sur amortissements des immobilisations corporelles",
    "7194": "Reprises sur provisions pour dépréciation des immobilisations",
    "7195": "Reprises sur provisions pour risques et charges",
    "7196": "Reprises sur provisions pour dépréciation de l'actif circulant",
    "7197": "Transferts des charges d'exploitation",
    "7198": "Reprises sur amortissements et provisions des exercices antérieurs",
    "7321": "Revenus des titres de participation",
    "7325": "Revenus des titres immobilisés",
    "7328": "Produits des titres de participation et des autres titres immobilisés des exercices antérieurs",
    "7331": "Gains de change propres à l'exercice",
    "7338": "Gains de change des exercices antérieurs",
    "7381": "Intérêts et produits assimilés",
    "7383": "Revenus des créances rattachées à des participations",
    "7384": "Revenus des titres et valeurs de placement",
    "7385": "Produits nets sur cessions de titres et valeurs de placement",
    "7386": "Escomptes obtenus",
    "7388": "Intérêts et autres produits financiers des exercices antérieurs",
    "7391": "Reprises sur amortissements des primes de remboursement des obligations",
    "7392": "Reprises sur provisions pour dépréciation des immobilisations financières",
    "7393": "Reprises sur provisions pour risques et charges financières",
    "7394": "Reprise sur provisions pour dépréciation des titres et valeurs de placement",
    "7396": "Reprises sur provisions pour dépréciation des comptes de trésorerie",
    "7397": "Transfert de charges financières",
    "7398": "Reprises sur dotations financières des exercices antérieurs",
    "7512": "Produits des cessions des immobilisations incorporelles",
    "7513": "Produits des cessions des immobilisations corporelles",
    "7514": "Produits des cessions des immobilisations financières (droits de propriété)",
    "7518": "Produits des cessions des immobilisations des exercices antérieurs",
    "7561": "Subventions d'équilibre reçues de l'exercice",
    "7568": "Subventions d'équilibre reçues des exercices antérieurs",
    "7577": "Reprises sur subventions d'investissement de l'exercice",
    "7578": "Reprises sur subventions d'investissement des exercices antérieurs",
    "7581": "Pénalités et dédits reçus",
    "7582": "Dégrèvement d'impôts (autres qu'impôts sur les résultats)",
    "7585": "Rentrées sur créances soldées",
    "7586": "Dons, libéralités et lots reçus",
    "7588": "Autres produits non courants des exercices antérieurs",
    "7591": "Reprises non courantes sur amortissements exceptionnels des immobilisations",
    "7594": "Reprises non courantes sur provisions réglementées",
    "7595": "Reprises non courantes sur provisions pour risques et charges",
    "7596": "Reprises non courantes sur provisions pour dépréciation",
    "7597": "Transferts de charges non courantes",
    "7598": "Reprises non courantes des exercices antérieurs",
}


def get_account_label(code_4: str) -> str:
    """Récupère l'intitulé d'un compte 4 chiffres."""
    return ACCOUNT_LABELS.get(code_4, "")
