"""
Mapping des postes (3 chiffres) vers leurs intitulés.
Source: Plan comptable marocain normalisé — Classes 1-9.
"""

POSTE_LABELS = {
    # CLASSE 1: COMPTES DE FINANCEMENT PERMANENT
    "111": "Capital social ou personnel",
    "112": "Primes d'émission, de fusion et d'apport",
    "113": "Ecarts de réévaluation",
    "114": "Réserve légale",
    "115": "Autres réserves",
    "116": "Report à nouveau",
    "118": "Résultats nets en instance d'affectation",
    "119": "Résultat net de l'exercice",
    "131": "Subventions d'investissement",
    "135": "Provisions réglementées",
    "141": "Emprunts obligataires",
    "148": "Autres dettes de financement",
    "151": "Provisions pour risques",
    "155": "Provisions pour charges",
    "160": "Comptes de liaison des établissements et succursales",
    "171": "Augmentation des créances immobilisées",
    "172": "Diminution des dettes de financement",
    # CLASSE 2: COMPTES D'ACTIF IMMOBILISE
    "211": "Frais préliminaires",
    "212": "Charges à répartir sur plusieurs exercices",
    "213": "Primes de remboursement des obligations",
    "221": "Immobilisation en recherche et développement",
    "222": "Brevets, marques, droits et valeurs similaires",
    "223": "Fonds commercial",
    "228": "Autres immobilisations incorporelles",
    "231": "Terrains",
    "232": "Constructions",
    "233": "Installations techniques, matériel et outillage",
    "234": "Matériel de transport",
    "235": "Mobilier, matériel de bureau et aménagements divers",
    "238": "Autres immobilisations corporelles",
    "239": "Immobilisations corporelles en cours",
    "241": "Prêts immobilisés",
    "248": "Autres créances financières",
    "251": "Titres de participation",
    "258": "Autres titres immobilisés",
    "271": "Diminution des créances immobilisées",
    "272": "Augmentation des dettes de financement",
    "281": "Amortissements des non-valeurs",
    "282": "Amortissements des immobilisations incorporelles",
    "283": "Amortissements des immobilisations corporelles",
    "292": "Provisions pour dépréciation des immobilisations incorporelles",
    "293": "Provisions pour dépréciation des immobilisations corporelles",
    "294": "Provisions pour dépréciation des prêts immobilisés",
    "295": "Provisions pour dépréciation des titres de participation",
    # CLASSE 3: COMPTES D'ACTIF CIRCULANT (HORS TRESORERIE)
    "311": "Marchandises",
    "312": "Matières et fournitures consommables",
    "313": "Produits en cours",
    "314": "Produits intermédiaires et produits résiduels",
    "315": "Produits finis",
    "341": "Fournisseurs débiteurs, avances et acomptes",
    "342": "Clients et comptes rattachés",
    "343": "Personnel - débiteur",
    "345": "Etat - débiteur",
    "346": "Comptes d'associés - débiteurs",
    "348": "Autres débiteurs",
    "349": "Comptes de régularisation - actif",
    "350": "Titres et valeurs de placement",
    "370": "Ecart de conversion - Actif (éléments circulants)",
    "391": "Provisions pour dépréciation des stocks",
    "394": "Provisions pour dépréciation des créances de l'actif circulant",
    "395": "Provisions pour dépréciation des titres et valeurs de placement",
    # CLASSE 4: COMPTES DU PASSIF CIRCULANT (HORS TRESORERIE)
    "441": "Fournisseurs et comptes rattachés",
    "442": "Clients créditeurs, avances et acomptes",
    "443": "Personnel - créditeur",
    "444": "Organismes sociaux",
    "445": "Etat - créditeur",
    "446": "Comptes d'associés - créditeurs",
    "448": "Autres créanciers",
    "449": "Comptes de régularisation - passif",
    "450": "Autres provisions pour risques et charges",
    "470": "Ecarts de conversion - passif (Eléments circulants)",
    # CLASSE 5: COMPTES DE TRESORERIE
    "511": "Chèques et valeurs à encaisser",
    "514": "Banques et chèques postaux (débiteurs)",
    "516": "Caisses, régies d'avances et accréditifs",
    "552": "Crédits d'escompte",
    "553": "Crédits de trésorerie",
    "554": "Banques (solde créditeur)",
    "590": "Provisions pour dépréciation des comptes de trésorerie",
    # CLASSE 6: COMPTES DE CHARGES
    "611": "Achats revendus de marchandises",
    "612": "Achats consommés de matières et fournitures",
    "613": "Locations et charges locatives",
    "614": "Etudes, recherches, transports, publicité, etc.",
    "616": "Impôts et taxes",
    "617": "Charges de personnel",
    "618": "Autres charges d'exploitation",
    "619": "Dotations d'exploitation",
    "631": "Charges d'intérêts",
    "633": "Pertes de change",
    "638": "Autres charges financières",
    "639": "Dotations financières",
    "651": "Valeurs nettes d'amortissements des immobilisations cédées",
    "656": "Subventions accordées",
    "658": "Autres charges non courantes",
    "659": "Dotations non courantes",
    "670": "Impôts sur les résultats",
    # CLASSE 7: COMPTES DE PRODUITS
    "711": "Ventes de marchandises",
    "712": "Ventes de biens et services produits",
    "713": "Variation des stocks de produits",
    "714": "Immobilisations produites par l'entreprise pour elle-même",
    "716": "Subventions d'exploitation",
    "718": "Autres produits d'exploitation",
    "719": "Reprises d'exploitation, transferts de charges",
    "732": "Produits des titres de participation et autres titres immobilisés",
    "733": "Gains de change",
    "738": "Intérêts et autres produits financiers",
    "739": "Reprises financières, transferts de charges",
    "751": "Produits des cessions d'immobilisations",
    "756": "Subventions d'équilibre",
    "757": "Reprise sur subventions d'investissements",
    "758": "Autres produits non courants",
    "759": "Reprises non courantes",
    # CLASSE 8: COMPTES DE RESULTATS
    "810": "Résultat d'exploitation",
    "811": "Marge brute",
    "814": "Valeur ajoutée",
    "817": "Excédent brut d'exploitation",
    "830": "Résultat financier",
    "840": "Résultat courant",
    "850": "Résultat non courant",
    "860": "Résultat avant impôts",
    "880": "Résultat après impôts",
    # CLASSE 9: COMPTES DE PRODUITS ET CHARGES REFLECHIS
    "903": "Stocks et provisions pour dépréciation des stocks réfléchis",
    "906": "Charges réfléchies",
    "907": "Produits réfléchis",
    "908": "Résultats réfléchis",
    "921": "Sections générales",
    "923": "Sections d'approvisionnement",
    "925": "Sections de production",
    "927": "Section de distribution",
    "928": "Autres sections analytiques",
    "933": "Coûts d'achat",
    "935": "Coûts de production",
    "938": "Autres coûts d'achat ou de production",
    "941": "Inventaire permanent des marchandises",
    "942": "Inventaire permanent des matières et fournitures consommables",
    "943": "Inventaire permanent des produits en cours",
    "944": "Inventaire permanent des produits intermédiaires et produits résiduels",
    "945": "Inventaire permanent des produits finis",
    "949": "Provisions sur dépréciation des stocks",
}


def get_poste_label(poste_code: str) -> str:
    """Retourne le libellé du poste (3 chiffres) ou une chaîne vide si non trouvé."""
    return POSTE_LABELS.get(poste_code, "")
